### PR TITLE
[Big test data] Add florida food inspection tests

### PR DESCRIPTION
**Pull request by orangejulius**
This adds a new directory, `big_test_cases`, for REALLLLY big test datasets. Using the [Florida food inspection dataset](https://github.com/riordan/what-is-geocode/raw/master/datasets/inspections-wo-geocodes.csv) from @riordan, we now have 51701 records to test against.

There are two big datasets, each with 51701 records. One uses an input like "full address, city, state, zip", the other uses "restaurant name, city, FL".

Random samples of 5% for addresses and 2% for name tests are added into the `test_cases` directory as a more manageable amount of tests for us to run more frequently.

We don't currently do that great on these tests at the moment based only on percentage of tests fully passing. Most of the address tests do at least seem to be in Florida, whereas the tests with the name don't even do that so well. There is, however, a lot of room for improvement by adding more normalizers to the fuzzy-tester. I already added two via pelias/fuzzy-tester#22 that remove ordinals and abbreviate street suffexes.

### CODE REVIEW

**Comment by dianashk** [comment]
Some of the tests have empty strings in coordinate values. How will that be treated and should we just not include the coordinate block in the test if values aren't available?

**Comment by riordan** [comment]
It's clear that this dataset isn't ground truth on these lon/lats either.
These blanks are places where the other geocoder failed to return.

So perhaps we import only the ones with lon/lats, but treat this as a
provisional dataset that we replace in a few months when we find a
comparable one with ground truth locations.

**Comment by orangejulius** [comment]
I just pushed two new commits that remove the coordinates section when a valid lat/lon aren't present. Since the full set of tests is in the "big_test_cases" directory, I'm happy to leave the test cases without lat/lon there.

However, I regenerated the smaller sample datasets that we might use for more regular testing, and ensured that they only include tests with a valid lat/lon.

There still isn't any support in the fuzzy-tester for dealing with the lat/lons, but we will at least have some data to play with when that time comes (soon!). So yes, I'm very much certain this dataset is provisional :)

**Comment by dianashk** [comment]
:+1:

**Pull request merged**
